Repository official-stockfish/fishtest, pull requests merged in 2019-12, with the labels that each got.

#454 Add robots.txt and favicon.ico
  fishtest/fishtest/static/favicon.ico
  fishtest/fishtest/static/robots.txt
  fishtest/fishtest/views.py
Labels: server

#453 Script to create indexes.
  fishtest/utils/create_indexes.py
Labels: server

#456 Speedup backup using mongodump options
  fishtest/utils/backup.sh
Labels: server

#457 Retire unused 'old_user_cache' MongoDb collection
  fishtest/fishtest/userdb.py
Labels: server

#459 Small speedup of SPSA by removing unneeded code
  fishtest/fishtest/rundb.py
Labels: server

#460 drop deleted index on runs
  fishtest/utils/create_indexes.py
Labels: server

#464 Red color when pending users
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/views.py
Labels: server

#466 Update reCAPTCHA public key
  fishtest/fishtest/templates/signup.mak
Labels: server

#449 Fix "divide by zero" warnings improving chi2 computation for unusual cases
  fishtest/fishtest/views.py
Labels: server

#467 Remove parameter tweak option for test bounds
  fishtest/fishtest/templates/tests_run.mak
Labels: server

#468 Calculate priority with number of active cores
  fishtest/fishtest/rundb.py
  fishtest/fishtest/templates/run_table.mak
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/templates/tests_run.mak
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
  fishtest/tests/test_rundb.py
Labels: server

#469 Minor fix for core counting
  fishtest/fishtest/rundb.py
Labels: server

#470 Minor fix for restarting SPSA
  fishtest/fishtest/rundb.py
Labels: server

#474 favicon.ico and robots.txt independent from CWD
  fishtest/fishtest/views.py
Labels: server

#471 Switch to new books and binaries repo
  worker/games.py
  worker/test_worker.py
Labels: worker

#351 Make the worker calculate the pentanomial frequencies.
  worker/games.py
  worker/worker.py
Labels: pentanomial, worker

#352 "get_results" now returns the aggregated pentanomial frequencies.
  fishtest/fishtest/rundb.py
Labels: pentanomial, server

#354 Include the pentanomial frequencies in the "elo results" widget.
  fishtest/fishtest/templates/elo_results.mak
  fishtest/fishtest/views.py
Labels: pentanomial, server

#373 Pentanomial stats
  fishtest/fishtest/__init__.py
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/fishtest/stat_util.py
  fishtest/fishtest/static/html/live_elo.html
  fishtest/fishtest/static/js/live_elo.js
  fishtest/fishtest/static/js/sprt_elo.js
  fishtest/fishtest/stats/LLRcalc.py
  fishtest/fishtest/stats/__init__.py
  fishtest/fishtest/stats/brentq.py
  fishtest/fishtest/stats/brownian.py
  fishtest/fishtest/stats/sprt.py
  fishtest/fishtest/stats/stat_util.py
  fishtest/fishtest/templates/tests_stats.mak
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: pentanomial, server

#477 Elo confidence intervals were inverted.
  fishtest/fishtest/templates/tests_stats.mak
Labels: server

#476 On the raw stats page give estimates for the DD and WL probabilities.
  fishtest/fishtest/templates/tests_stats.mak
Labels: server

#479 Use logistic elo in fishtest.
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/fishtest/static/html/sprt_elo.js.mem
  fishtest/fishtest/static/js/live_elo.js
  fishtest/fishtest/stats/stat_util.py
  fishtest/fishtest/templates/tests_run.mak
  fishtest/fishtest/templates/tests_stats.mak
  fishtest/fishtest/views.py
Labels: server
