Repository official-stockfish/fishtest, pull requests merged in 2019-11, with the labels that each got.

#43 Fix mako templates on Pyramid 1.5
  fishtest/fishtest/__init__.py
  fishtest/setup.py
Labels: server

#394 Setup Pyramid to work with nginx
  fishtest/production.ini
Labels: https, server

#429 Update the backup process for Ubuntu 18.04
  fishtest/utils/backup.sh
Labels: server

#430 Add boto package to fishtest setup
  fishtest/setup.py
Labels: server

#413 exit on existance of signal file
  worker/worker.py
Labels: worker

#434 Add a script to copy runs to old_runs
  fishtest/utils/move2old_runs.py
Labels: server

#431 Update and cleanup for Ubuntu 18.04
  .gitignore
  README.md
  SETUP
  fishtest/start.sh
  fishtest/start_dev.sh
  fishtest/utils/backup.sh
  fishtest/utils/clone_fish.py
  fishtest/utils/create_pgndb.py
  fishtest/utils/current.py
  fishtest/utils/delta_update_users.py
  fishtest/utils/index_pending.py
  fishtest/utils/purge_pgn.py
  fishtest/utils/scavenge.py
  fishtest/utils/update_users.py
Labels: server

#439 sort old runs for viewing
  fishtest/fishtest/rundb.py
Labels: server

#436 Python script to time some db queries
  fishtest/utils/test_queries.py
Labels: server

#442 Handle some 2013 runs without 'worker_info'
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#443 Speed up finished runs MongoDb query
  fishtest/fishtest/rundb.py
  fishtest/fishtest/views.py
Labels: server

#447 Fix delete run
  fishtest/fishtest/rundb.py
  fishtest/fishtest/views.py
Labels: server

#444 Enhance test_queries.py to include explains and to test hints
  fishtest/utils/test_queries.py
Labels: server

#451 Speedup computation of info pages
  fishtest/fishtest/views.py
Labels: server
