Repository official-stockfish/fishtest, pull requests merged in 2020-07, with the labels that each got.

#713 Try to stop test after a cutechess warning
  worker/games.py
Labels: enhancement, worker

#718 Fix subprocess.Popen.poll() check
  worker/games.py
Labels: bug, worker

#719 Enable a new algorithm for choosing SPSA hyperparameters.
  fishtest/fishtest/static/js/spsa_new.js
  fishtest/fishtest/templates/tests_run.mak
Labels: enhancement, server

#723 Update tests_view.mak
  fishtest/fishtest/templates/tests_view.mak
Labels: enhancement, server

#726 Add failed flag for runs
  fishtest/fishtest/api.py
  fishtest/fishtest/views.py
Labels: enhancement, server

#725 fix strip_run()
  fishtest/fishtest/api.py
Labels: bug, server

#722 Clean up parse_cutechess_output()
  worker/games.py
  worker/worker.py
Labels: worker

#728 Raise worker version to 81 (server side)
  fishtest/fishtest/api.py
Labels: worker
