Repository official-stockfish/fishtest, pull requests merged in 2020-06, with the labels that each got.

#698 Strip non utf-8 characters from PGN files
  worker/worker.py
Labels: worker

#705 Improve signup message
  fishtest/fishtest/templates/signup.mak
  fishtest/fishtest/views.py
Labels: gui, server

#703 Add a default test contempt parameter
  fishtest/fishtest/templates/tests_run.mak
Labels: gui, server

#709 List 25 items on view pages
  fishtest/fishtest/views.py
Labels: enhancement, server

#715 Handle longer (> 7 digits) bench signatures
  fishtest/fishtest/views.py
Labels: bug, server

#711 Remove tasks from run data in actions
  fishtest/fishtest/views.py
  fishtest/utils/compact_actions.py
Labels: enhancement, server

#717 Make parsing of spsa parameters resistant to blank lines.
  fishtest/fishtest/views.py
Labels: server
