Repository official-stockfish/fishtest, pull requests merged in 2020-05, with the labels that each got.

#655 Enforce even sized worker updates.
  fishtest/fishtest/rundb.py
  fishtest/tests/test_api.py
  fishtest/tests/test_rundb.py
Labels: bug, enhancement, server

#658 A quick attempt at fixing https://github.com/glinscott/fishtest/issue…
  fishtest/fishtest/templates/tests_run.mak
Labels: bug

#657 Some code cleanup in the worker
  worker/games.py
  worker/worker.py
Labels: enhancement, worker

#660 Remove unused list
  fishtest/fishtest/rundb.py
Labels: server

#662 Limit worker API usage
  fishtest/fishtest/rundb.py
  worker/worker.py
Labels: scaling, server, worker

#665 Show link to original test when viewing a rescheduled test
  fishtest/fishtest/rundb.py
  fishtest/fishtest/templates/tests_run.mak
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: enhancement, gui, server

#668 Handle rate_limit API call failure
  worker/games.py
  worker/worker.py
Labels: enhancement, worker

#667 Fix some chars showing up as html entities in test commit msgs
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: bug, gui, server

#676 Change default machine limit to 16
  fishtest/fishtest/userdb.py
Labels: server

#678 Query for unfinished_runs with only the id attribute
  fishtest/fishtest/rundb.py
Labels: enhancement, server

#687 Less logging: no task queue warnings
  fishtest/production.ini
Labels: server

#689 Use 10 digits of the sha
  fishtest/fishtest/helpers.py
  fishtest/fishtest/views.py
  worker/games.py
  worker/worker.py
Labels: server, worker

#691 Use 10 digits of the sha. Part 2.
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#692 Adjust Elo range on dial for live_elo
  fishtest/fishtest/static/html/SPRTcalculator.html
  fishtest/fishtest/static/html/live_elo.html
  fishtest/fishtest/static/js/live_elo.js
Labels: server

#693 update live_elo js version
  fishtest/fishtest/static/html/live_elo.html
Labels: bug, server

#696 Add error check for time control
  fishtest/fishtest/views.py
Labels: server
