Repository official-stockfish/fishtest, pull requests merged in 2020-04, with the labels that each got.

#555 Single click SMP tests
  fishtest/fishtest/templates/tests_run.mak
Labels: server

#556 Move "Test repo" field right under "Test branch"
  fishtest/fishtest/templates/tests_run.mak
Labels: server

#558 Show github diff above tasks section on test pages
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#559 Show result of comparing base branch with master on pending tests
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#561 Add colored syntax highlighting to diffs
  fishtest/fishtest/static/css/highlight.github.css
  fishtest/fishtest/static/js/highlight.diff.min.js
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#562 Show # of active tests on homepage
  fishtest/fishtest/templates/tests.mak
Labels: server

#565 Validate book is in official books repo when submitting tests
  fishtest/fishtest/views.py
Labels: server

#567 Don't show base branch comparison message for old finished tests
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#568 Server-side check for whether master diff matches base branch
  fishtest/fishtest/rundb.py
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: server

#566 Show number of github comments on the diff when viewing tests
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/run_table.mak
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#571 Some css and js cleanup
  fishtest/fishtest/__init__.py
  fishtest/fishtest/helpers.py
  fishtest/fishtest/static/css/application.css
  fishtest/fishtest/static/css/bootstrap-responsive.css
  fishtest/fishtest/static/css/bootstrap-responsive.min.css
  fishtest/fishtest/static/css/bootstrap.css
  fishtest/fishtest/static/css/bootstrap.min.css
  fishtest/fishtest/static/img/glyphicons-halflings-white.png
  fishtest/fishtest/static/img/glyphicons-halflings.png
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/static/js/bootstrap.js
  fishtest/fishtest/static/js/bootstrap.min.js
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/run_table.mak
  fishtest/fishtest/templates/signup.mak
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/templates/tests_run.mak
  fishtest/fishtest/templates/tests_stats.mak
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: server

#573 Improve pending_hours estimate
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/views.py
Labels: server

#570 Fix slow queries due to missing MongoDB indexes
  fishtest/fishtest/rundb.py
  fishtest/utils/create_indexes.py
Labels: server

#576 Minor sidebar cosmetic update
  fishtest/fishtest/static/css/application.css
  fishtest/fishtest/templates/base.mak
Labels: server

#583 Cache pending for 1s instead of 60s
  fishtest/fishtest/userdb.py
Labels: server

#581 Handle Show/Hide cookies for cached content
  fishtest/fishtest/views.py
Labels: server

#584 Lazy-load machines table on homepage if hidden by user
  fishtest/fishtest/__init__.py
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/machines_table.mak
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/views.py
Labels: server

#588 Use different titles for finished test pages
  fishtest/fishtest/__init__.py
  fishtest/fishtest/rundb.py
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/run_table.mak
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/templates/tests_finished.mak
  fishtest/fishtest/views.py
Labels: server

#591 Fix unnecessary expensive work on tests pages past page 1
  fishtest/fishtest/templates/run_tables.mak
  fishtest/fishtest/templates/tests.mak
  fishtest/fishtest/templates/tests_user.mak
  fishtest/fishtest/views.py
Labels: server

#589 Add initial tests for fishtest API
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/tests/test_api.py
Labels: server

#592 Add button to copy command for fetching diff and git-apply'ing it
  fishtest/fishtest/static/img/clipboard.png
  fishtest/fishtest/templates/tests_view.mak
Labels: server

#597 Fix "javascipt" typo
  fishtest/fishtest/templates/tests_view.mak
Labels: bug, server

#574 Stop using old_runs collection for runs queries
  fishtest/fishtest/rundb.py
  fishtest/fishtest/views.py
  fishtest/tests/test_rundb.py
  fishtest/utils/create_indexes.py
Labels: server

#595 Iterate through runs using range queries in delta_update_users.py
  fishtest/utils/delta_update_users.py
  fishtest/utils/update_users.py
Labels: server

#594 Fix some pymongo deprecation warnings
  fishtest/fishtest/actiondb.py
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/fishtest/userdb.py
  fishtest/tests/test_rundb.py
Labels: server

#598 Add yellow finished tests page and sidebar link
  fishtest/fishtest/rundb.py
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/tests_finished.mak
  fishtest/fishtest/views.py
Labels: enhancement, server

#603 Remove unused move2old_runs.py script
  fishtest/utils/move2old_runs.py
Labels: server

#601 Scale down update_task request frequency by 2x
  fishtest/fishtest/api.py
  worker/games.py
  worker/worker.py
Labels: scaling, worker

#586 Limit max number of worker cores for a SPSA tuning job
  fishtest/fishtest/rundb.py
Labels: scaling, server

#572 Update layout of 'create new test' page
  fishtest/fishtest/templates/tests_run.mak
  fishtest/fishtest/views.py
Labels: server

#606 Center header text on 'create new test' page
  fishtest/fishtest/templates/tests_run.mak
Labels: enhancement, gui

#611 Cache flag lookups
  fishtest/fishtest/api.py
Labels: bug, server

#608 Show error messages in red instead of green
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/views.py
Labels: gui, server

#607 Add more API tests and simplify API code
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/tests/test_api.py
  fishtest/tests/test_users.py
Labels: enhancement, server

#613 Persistent logins and http-only auth cookies
  fishtest/fishtest/__init__.py
  fishtest/fishtest/templates/login.mak
  fishtest/fishtest/views.py
Labels: server

#614 Add index to flag_cache, auto-expire after 7 days, new create_indexes.py
  fishtest/fishtest/api.py
  fishtest/fishtest/userdb.py
  fishtest/utils/create_indexes.py
  fishtest/utils/delta_update_users.py
Labels: server

#616 Fallback to a default tests_repo for old runs
  fishtest/fishtest/helpers.py
  fishtest/fishtest/templates/tests_view.mak
Labels: bug, server

#619 Bring back default values for SPSA params
  fishtest/fishtest/templates/tests_run.mak
Labels: server

#617 Python < 3.6 compatibility fix
  fishtest/fishtest/rundb.py
Labels: bug, server

#621 Simplify displaying params in SPSA table
  fishtest/fishtest/static/css/application.css
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: gui, server

#623 Add some space above flash (success/error) messages
  fishtest/fishtest/static/css/application.css
  fishtest/fishtest/templates/base.mak
Labels: enhancement, gui, server

#622 Go to /tests/run after login if logged-out user tried going there
  fishtest/fishtest/views.py
Labels: enhancement, gui, server

#629 Prevent 'create new test' form creating duplicate tests
  fishtest/fishtest/templates/tests_run.mak
Labels: enhancement, gui, server

#626 Disable base branch/signature fields for SPSA tests
  fishtest/fishtest/templates/tests_run.mak
Labels: enhancement, gui, server

#630 When switching away from SPSA test type, use initial base values
  fishtest/fishtest/templates/tests_run.mak
Labels: bug, gui, server

#631 Hide master diff link if base branch is same as stockfish master
  fishtest/fishtest/templates/tests_view.mak
Labels: enhancement, gui, server

#633 Set page title on test pages to test type+branches
  fishtest/fishtest/templates/tests_view.mak
Labels: enhancement, gui, server

#635 Adjust time estimate
  fishtest/fishtest/views.py
  fishtest/utils/delta_update_users.py
  worker/games.py
Labels: enhancement, server

#638 Link to master diff for SPSA runs
  fishtest/fishtest/helpers.py
  fishtest/fishtest/templates/tests_view.mak
Labels: enhancement, gui, server

#639 Update page titles to match browser tab names
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: enhancement, gui, server

#640 Link to your tests in the sidebar for logged-in users
  fishtest/fishtest/templates/base.mak
Labels: enhancement, gui, server

#632 Homepage visits no longer cause writes to runs collection
  fishtest/fishtest/rundb.py
  fishtest/fishtest/util.py
  fishtest/fishtest/views.py
  fishtest/tests/test_api.py
  fishtest/utils/delta_update_users.py
Labels: scaling, server

#641 Enable modifying auto-purge on tests_view pages
  fishtest/fishtest/templates/tests_view.mak
  fishtest/fishtest/views.py
Labels: enhancement, gui, server

#643 Fix order for purging PGNs
  fishtest/utils/purge_pgn.py
Labels: bug, server

#644 Provide remote_addr="127.0.0.1" argument to DummyRequest in test_user…
  fishtest/tests/test_users.py
Labels: bug, server

#645 Limit concurrent flag queries
  fishtest/fishtest/api.py
Labels: scaling, server

#627 Worker changes to allow batching.
  worker/games.py
Labels: scaling, worker

#628 Server changes to set the batch size for sprt tests.
  fishtest/fishtest/rundb.py
  fishtest/fishtest/stats/stat_util.py
  fishtest/fishtest/views.py
  fishtest/tests/test_api.py
Labels: scaling, server

#649 Enable submit test button if arriving from browser back button
  fishtest/fishtest/templates/tests_run.mak
Labels: bug, gui, server

#650 Fix TC parsing for itp
  fishtest/fishtest/rundb.py
Labels: bug, server

#656 Fixes some issues with test submission. Including #652.
  fishtest/fishtest/views.py
Labels: bug, server
