Repository official-stockfish/fishtest, pull requests merged in 2020-10, with the labels that each got.

#797 Fix SyntaxWarning: "is" with a literal
  fishtest/fishtest/views.py
Labels: bug, server

#798 Fix some flake8 warnings
  worker/games.py
  worker/worker.py
Labels: enhancement, worker

#800 Disable concurrent tranfers for aws s3
  fishtest/utils/backup.sh
Labels: enhancement, server

#794 Restore waitress default for connections/threads
  fishtest/production.ini
Labels: server

#803 NN upload accept .nnue
  fishtest/fishtest/templates/nn_upload.mak
Labels: enhancement, nnue, server

#801 Use the string format method
  worker/games.py
  worker/updater.py
  worker/worker.py
Labels: enhancement, worker

#804 Raise version to 87 (server side)
  fishtest/fishtest/api.py
Labels: server

#805 Set cores to "0" for pending runs
  fishtest/fishtest/rundb.py
Labels: enhancement, server

#806 Enable toggling between light and dark mode
  fishtest/fishtest/static/css/application.css
  fishtest/fishtest/static/css/theme.dark.css
  fishtest/fishtest/static/html/live_elo.html
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/signup.mak
  fishtest/fishtest/templates/tests_stats.mak
Labels: enhancement, gui, server

#807 Use sun/moon icons for actions
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/templates/base.mak
Labels: enhancement, gui, server

#808 Update jquery to 3.5.1
  fishtest/fishtest/templates/base.mak
Labels: enhancement, server

#813 Raise worker version to 88 (server side)
  fishtest/fishtest/api.py
Labels: server

#820 Fix readability of test tasks table in night mode
  fishtest/fishtest/static/css/theme.dark.css
  fishtest/fishtest/static/html/SPRTcalculator.html
  fishtest/fishtest/static/html/live_elo.html
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/templates/base.mak
Labels: enhancement, gui

#817 Add NN paging and show/hide non default nets
  fishtest/fishtest/rundb.py
  fishtest/fishtest/static/js/application.js
  fishtest/fishtest/templates/base.mak
  fishtest/fishtest/templates/nns.mak
  fishtest/fishtest/views.py
Labels: enhancement, nnue, server

#824 Improve words and style for nets pagination arrows
  fishtest/fishtest/templates/nns.mak
Labels: enhancement, gui, nnue, server

#821 Simple worker heartbeat to detect dead workers
  fishtest/fishtest/__init__.py
  fishtest/fishtest/api.py
  fishtest/fishtest/rundb.py
  fishtest/tests/test_api.py
  fishtest/utils/scavenge.py
  worker/games.py
  worker/worker.py
Labels: worker

#828 Make flush cache more robust and fix pentanomial
  fishtest/fishtest/rundb.py
Labels: bug, server

#831 Fix fish.exit with heartbeat
  worker/worker.py
Labels: bug, worker

#830 Fix race condition, cache cleanup and obsolete Mongo API calls
  fishtest/fishtest/rundb.py
Labels: bug, server

#829 Raise worker version to 90 (server side)
  fishtest/fishtest/api.py
Labels: server, wip

#832 Retire utils/scavenge.py
  fishtest/utils/scavenge.py
Labels: server

#833 Do not assign workers with large concurrency to STC jobs
  fishtest/fishtest/rundb.py
Labels: bug, server, wip

#836 Delay scavenge on boot
  server/fishtest/rundb.py
Labels: enhancement, server

#835 Save some space in testing dir
  worker/games.py
Labels: enhancement, worker

#838 Replace sys.exit() by os._exit() to stop heartbeat
  worker/games.py
  worker/worker.py
Labels: bug, worker

#839 Remove the network files from the backup folder
  worker/updater.py
Labels: enhancement, worker

#840 Improve output and little code clean up
  worker/games.py
  worker/worker.py
Labels: enhancement, worker

#843 Fix worker test: exiting early when given no args
  worker/test_worker.py
Labels: bug, server

#844 Make flush buffers more robust
  server/fishtest/rundb.py
Labels: bug, server

#841 Raise worker version to 91 (server side)
  server/fishtest/api.py
Labels: server

#845 Add --fleet/--use_all_cores worker option
  worker/worker.py
Labels: enhancement, worker

#848 Fix logic for cli positional arguments
  worker/worker.py
Labels: bug, worker
